// <auto-generated />
using System;
using DiarioX.Server.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiarioX.Server.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260926043409_AddChamadas")]
    partial class AddChamadas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("cep");

                    b.Property<string>("CertidaoNascimento")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("certidao_nascimento");

                    b.Property<string>("CorRaca")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cor_raca");

                    b.Property<string>("CpfAluno")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf_aluno");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("EnderecoCompleto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("endereco_completo");

                    b.Property<int>("EscolaId")
                        .HasColumnType("integer");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("matricula");

                    b.Property<bool>("NecessidadeEspecial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("necessidade_especial");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.Property<string>("ResponsavelCpf1")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("responsavel_cpf1");

                    b.Property<string>("ResponsavelNome1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("responsavel_nome1");

                    b.Property<string>("ResponsavelNome2")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("responsavel_nome2");

                    b.Property<string>("ResponsavelTelefone1")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("responsavel_telefone1");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sexo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("ATIVO_AGUARDANDO_ENTURMACAO")
                        .HasColumnName("status");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EscolaId")
                        .HasDatabaseName("IX_alunos_escola_id");

                    b.HasIndex("TenantId", "CpfAluno")
                        .IsUnique()
                        .HasDatabaseName("IX_alunos_cpf_aluno")
                        .HasFilter("cpf_aluno IS NOT NULL");

                    b.HasIndex("TenantId", "Matricula")
                        .IsUnique()
                        .HasDatabaseName("IX_alunos_matricula");

                    b.HasIndex("TenantId", "Nome", "DataNascimento", "ResponsavelNome1")
                        .IsUnique()
                        .HasDatabaseName("IX_alunos_nome_nascimento_responsavel")
                        .HasFilter("cpf_aluno IS NULL");

                    b.ToTable("alunos", null, t =>
                        {
                            t.HasCheckConstraint("CK_alunos_sexo", "sexo IN ('MASCULINO', 'FEMININO')");
                        });
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.AlunoTurma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer")
                        .HasColumnName("aluno_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("data_fim");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TurmaId")
                        .HasColumnType("integer")
                        .HasColumnName("turma_id");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId")
                        .IsUnique()
                        .HasDatabaseName("IX_alunos_turmas_aluno_ativo")
                        .HasFilter("data_fim IS NULL");

                    b.HasIndex("TenantId");

                    b.HasIndex("AlunoId", "DataInicio")
                        .HasDatabaseName("IX_alunos_turmas_aluno_inicio");

                    b.HasIndex("TurmaId", "DataInicio", "DataFim")
                        .HasDatabaseName("IX_alunos_turmas_turma_periodo");

                    b.ToTable("alunos_turmas", null, t =>
                        {
                            t.HasCheckConstraint("CK_alunos_turmas_periodo", "data_fim IS NULL OR data_fim >= data_inicio");
                        });
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.AnoLetivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoReferencia")
                        .HasColumnType("integer")
                        .HasColumnName("ano_referencia");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<DateOnly>("DataTermino")
                        .HasColumnType("date")
                        .HasColumnName("data_termino");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TipoPeriodo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_periodo");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AnoReferencia")
                        .IsUnique()
                        .HasDatabaseName("IX_anos_letivos_ano_referencia");

                    b.ToTable("anos_letivos", null, t =>
                        {
                            t.HasCheckConstraint("CK_anos_letivos_tipo_periodo", "tipo_periodo IN ('BIMESTRAL', 'TRIMESTRAL', 'SEMESTRAL')");
                        });
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.Chamada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtualizadoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("atualizado_por_usuario_id");

                    b.Property<string>("Conteudo")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("conteudo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("integer")
                        .HasColumnName("disciplina_id");

                    b.Property<int>("QuantidadeAulas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantidade_aulas");

                    b.Property<int>("RegistradoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("registrado_por_usuario_id");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TurmaId")
                        .HasColumnType("integer")
                        .HasColumnName("turma_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AtualizadoPorUsuarioId");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("RegistradoPorUsuarioId");

                    b.HasIndex("TurmaId");

                    b.HasIndex("TenantId", "TurmaId", "DisciplinaId", "Data")
                        .IsUnique()
                        .HasDatabaseName("IX_chamadas_turma_disciplina_data");

                    b.ToTable("chamadas", null, t =>
                        {
                            t.HasCheckConstraint("CK_chamadas_quantidade_aulas", "quantidade_aulas BETWEEN 1 AND 6");
                        });
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.ChamadaAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer")
                        .HasColumnName("aluno_id");

                    b.Property<int>("ChamadaId")
                        .HasColumnType("integer")
                        .HasColumnName("chamada_id");

                    b.Property<string>("Justificativa")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("justificativa");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("situacao");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId")
                        .HasDatabaseName("IX_chamadas_alunos_aluno");

                    b.HasIndex("TenantId");

                    b.HasIndex("ChamadaId", "AlunoId")
                        .IsUnique()
                        .HasDatabaseName("IX_chamadas_alunos_chamada_aluno");

                    b.ToTable("chamadas_alunos", null, t =>
                        {
                            t.HasCheckConstraint("CK_chamadas_alunos_situacao", "situacao IN ('PRESENTE', 'FALTA', 'FALTA_JUSTIFICADA')");
                        });
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativa");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .HasDatabaseName("IX_disciplinas_nome");

                    b.HasIndex("TenantId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_disciplinas_codigo");

                    b.ToTable("disciplinas", (string)null);
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.DisciplinaEtapaEnsino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("integer")
                        .HasColumnName("disciplina_id");

                    b.Property<int>("EtapaEnsinoId")
                        .HasColumnType("integer")
                        .HasColumnName("etapa_ensino_id");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("EtapaEnsinoId");

                    b.HasIndex("TenantId");

                    b.HasIndex("DisciplinaId", "EtapaEnsinoId")
                        .IsUnique()
                        .HasDatabaseName("IX_disciplinas_etapas_ensino_unicidade");

                    b.ToTable("disciplinas_etapas_ensino", (string)null);
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.EmailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("assunto");

                    b.Property<string>("CorpoHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("corpo_html");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DestinatarioEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("destinatario_email");

                    b.Property<string>("DestinatarioNome")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("destinatario_nome");

                    b.Property<DateTime?>("EnviadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviado_em");

                    b.Property<string>("ErroMensagem")
                        .HasColumnType("text")
                        .HasColumnName("erro_mensagem");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDENTE")
                        .HasColumnName("status");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("template_id");

                    b.Property<int>("Tentativas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tentativas");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_email_logs_created_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_email_logs_status");

                    b.HasIndex("TemplateId");

                    b.ToTable("email_logs", null, t =>
                        {
                            t.HasCheckConstraint("CK_email_logs_status", "status IN ('PENDENTE', 'ENVIADO', 'FALHOU')");
                        });
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("assunto");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("CorpoHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("corpo_html");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.PrimitiveCollection<string[]>("Variaveis")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("variaveis")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("IX_email_templates_nome");

                    b.ToTable("email_templates", (string)null);
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.Escola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<string>("CodigoInep")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_inep");

                    b.Property<int?>("DiretorId")
                        .HasColumnType("integer")
                        .HasColumnName("diretor_id");

                    b.Property<string>("EmailInstitucional")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email_institucional");

                    b.Property<string>("EnderecoCompleto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("endereco_completo");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("municipio");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ATIVO")
                        .HasColumnName("status");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("DiretorId");

                    b.HasIndex("TenantId", "CodigoInep")
                        .IsUnique()
                        .HasDatabaseName("IX_escolas_codigo_inep");

                    b.ToTable("escolas", null, t =>
                        {
                            t.HasCheckConstraint("CK_escolas_status", "status IN ('ATIVO', 'INATIVO')");
                        });
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.EtapaEnsino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdadeRecomendada")
                        .HasColumnType("integer")
                        .HasColumnName("idade_recomendada");

                    b.Property<int>("ModalidadeEnsinoId")
                        .HasColumnType("integer")
                        .HasColumnName("modalidade_ensino_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int>("OrdemCronologica")
                        .HasColumnType("integer")
                        .HasColumnName("ordem_cronologica");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sigla");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ModalidadeEnsinoId", "Nome")
                        .IsUnique()
                        .HasDatabaseName("IX_etapas_ensino_modalidade_nome");

                    b.HasIndex("ModalidadeEnsinoId", "OrdemCronologica")
                        .IsUnique()
                        .HasDatabaseName("IX_etapas_ensino_modalidade_ordem");

                    b.HasIndex("TenantId", "Sigla")
                        .IsUnique()
                        .HasDatabaseName("IX_etapas_ensino_sigla");

                    b.ToTable("etapas_ensino", (string)null);
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.ModalidadeEnsino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoMec")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_mec");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sigla");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ATIVO")
                        .HasColumnName("status");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Nome")
                        .IsUnique()
                        .HasDatabaseName("IX_modalidades_ensino_nome");

                    b.HasIndex("TenantId", "Sigla")
                        .IsUnique()
                        .HasDatabaseName("IX_modalidades_ensino_sigla");

                    b.ToTable("modalidades_ensino", null, t =>
                        {
                            t.HasCheckConstraint("CK_modalidades_ensino_status", "status IN ('ATIVO', 'INATIVO')");
                        });
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_password_reset_tokens_token_hash");

                    b.HasIndex("UserId");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("perfis", (string)null);
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.PerfilPermissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PerfilId")
                        .HasColumnType("integer")
                        .HasColumnName("perfil_id");

                    b.Property<string>("Permissao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permissao");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.HasIndex("TenantId", "PerfilId", "Permissao")
                        .IsUnique()
                        .HasDatabaseName("IX_perfis_permissoes_tenant_perfil_permissao");

                    b.ToTable("perfis_permissoes", (string)null);
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.PeriodoAvaliativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoLetivoId")
                        .HasColumnType("integer")
                        .HasColumnName("ano_letivo_id");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<DateOnly>("DataTermino")
                        .HasColumnType("date")
                        .HasColumnName("data_termino");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("AnoLetivoId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("IX_periodos_avaliativos_ano_numero");

                    b.ToTable("periodos_avaliativos", (string)null);
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DataAdmissao")
                        .HasColumnType("date")
                        .HasColumnName("data_admissao");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Matricula")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("matricula");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ATIVO")
                        .HasColumnName("situacao");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("TenantId", "Cpf")
                        .IsUnique()
                        .HasDatabaseName("IX_professores_cpf");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("IX_professores_email");

                    b.HasIndex("TenantId", "Matricula")
                        .IsUnique()
                        .HasDatabaseName("IX_professores_matricula");

                    b.ToTable("professores", null, t =>
                        {
                            t.HasCheckConstraint("CK_professores_situacao", "situacao IN ('ATIVO', 'INATIVO', 'AFASTADO', 'LICENCIADO')");
                        });
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.ProfessorAlocacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativa");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("integer")
                        .HasColumnName("disciplina_id");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer")
                        .HasColumnName("professor_id");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TurmaId")
                        .HasColumnType("integer")
                        .HasColumnName("turma_id");

                    b.HasKey("Id");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TurmaId", "DisciplinaId")
                        .IsUnique()
                        .HasDatabaseName("IX_professor_alocacoes_turma_disciplina_ativa")
                        .HasFilter("ativa = TRUE");

                    b.HasIndex("ProfessorId", "TurmaId", "DisciplinaId")
                        .IsUnique()
                        .HasDatabaseName("IX_professor_alocacoes_professor_turma_disciplina");

                    b.ToTable("professor_alocacoes", (string)null);
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.ProfessorDisciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("integer");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("DisciplinaId")
                        .HasDatabaseName("IX_professor_disciplinas_disciplina_id");

                    b.HasIndex("ProfessorId")
                        .HasDatabaseName("IX_professor_disciplinas_professor_id");

                    b.HasIndex("TenantId");

                    b.HasIndex("ProfessorId", "DisciplinaId")
                        .IsUnique()
                        .HasDatabaseName("IX_professor_disciplinas_unique");

                    b.ToTable("professor_disciplinas", (string)null);
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.ProfessorEscola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("EscolaId")
                        .HasColumnType("integer");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("EscolaId")
                        .HasDatabaseName("IX_professor_escolas_escola_id");

                    b.HasIndex("ProfessorId")
                        .HasDatabaseName("IX_professor_escolas_professor_id");

                    b.HasIndex("TenantId");

                    b.HasIndex("ProfessorId", "EscolaId")
                        .IsUnique()
                        .HasDatabaseName("IX_professor_escolas_unique");

                    b.ToTable("professor_escolas", (string)null);
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ATIVO")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_tenants_slug");

                    b.ToTable("tenants", null, t =>
                        {
                            t.HasCheckConstraint("CK_tenants_status", "status IN ('ATIVO', 'INATIVO')");
                        });
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoLetivoId")
                        .HasColumnType("integer")
                        .HasColumnName("ano_letivo_id");

                    b.Property<int>("EscolaId")
                        .HasColumnType("integer")
                        .HasColumnName("escola_id");

                    b.Property<int>("EtapaEnsinoId")
                        .HasColumnType("integer")
                        .HasColumnName("etapa_ensino_id");

                    b.Property<int>("ModalidadeEnsinoId")
                        .HasColumnType("integer")
                        .HasColumnName("modalidade_ensino_id");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_completo");

                    b.Property<string>("NomeIdentificador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_identificador");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ATIVO")
                        .HasColumnName("status");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("turno");

                    b.Property<int>("VagasOfertadas")
                        .HasColumnType("integer")
                        .HasColumnName("vagas_ofertadas");

                    b.HasKey("Id");

                    b.HasIndex("EscolaId");

                    b.HasIndex("EtapaEnsinoId");

                    b.HasIndex("ModalidadeEnsinoId");

                    b.HasIndex("TenantId");

                    b.HasIndex("AnoLetivoId", "EscolaId", "EtapaEnsinoId", "NomeIdentificador", "Turno")
                        .IsUnique()
                        .HasDatabaseName("IX_turmas_unicidade");

                    b.ToTable("turmas", null, t =>
                        {
                            t.HasCheckConstraint("CK_turmas_status", "status IN ('ATIVO', 'INATIVO')");

                            t.HasCheckConstraint("CK_turmas_turno", "turno IN ('MANHA', 'TARDE', 'NOITE', 'INTEGRAL')");

                            t.HasCheckConstraint("CK_turmas_vagas_ofertadas", "vagas_ofertadas > 0");
                        });
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_attempts");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ATIVO")
                        .HasColumnName("status");

                    b.Property<int?>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acesso");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("IX_users_cpf_global")
                        .HasFilter("tenant_id IS NULL");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_users_email_global")
                        .HasFilter("tenant_id IS NULL");

                    b.HasIndex("TenantId", "Cpf")
                        .IsUnique()
                        .HasDatabaseName("IX_users_tenant_cpf")
                        .HasFilter("tenant_id IS NOT NULL");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("IX_users_tenant_email")
                        .HasFilter("tenant_id IS NOT NULL");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("CK_users_status", "status IN ('ATIVO', 'INATIVO', 'BLOQUEADO')");
                        });
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.UsuarioPerfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EscolaId")
                        .HasColumnType("integer")
                        .HasColumnName("escola_id");

                    b.Property<int>("PerfilId")
                        .HasColumnType("integer")
                        .HasColumnName("perfil_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("EscolaId");

                    b.HasIndex("PerfilId");

                    b.HasIndex("UsuarioId", "PerfilId")
                        .IsUnique()
                        .HasDatabaseName("IX_usuarios_perfis_global")
                        .HasFilter("escola_id IS NULL");

                    b.HasIndex("UsuarioId", "PerfilId", "EscolaId")
                        .IsUnique()
                        .HasDatabaseName("IX_usuarios_perfis_escola")
                        .HasFilter("escola_id IS NOT NULL");

                    b.ToTable("usuarios_perfis", (string)null);
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.Aluno", b =>
                {
                    b.HasOne("DiarioX.Server.Domain.Entities.Escola", "Escola")
                        .WithMany()
                        .HasForeignKey("EscolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_alunos_escolas");

                    b.HasOne("DiarioX.Server.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Escola");
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.AlunoTurma", b =>
                {
                    b.HasOne("DiarioX.Server.Domain.Entities.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiarioX.Server.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiarioX.Server.Domain.Entities.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.AnoLetivo", b =>
                {
                    b.HasOne("DiarioX.Server.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.Chamada", b =>
                {
                    b.HasOne("DiarioX.Server.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AtualizadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DiarioX.Server.Domain.Entities.Disciplina", "Disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiarioX.Server.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RegistradoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiarioX.Server.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiarioX.Server.Domain.Entities.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Disciplina");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.ChamadaAluno", b =>
                {
                    b.HasOne("DiarioX.Server.Domain.Entities.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiarioX.Server.Domain.Entities.Chamada", "Chamada")
                        .WithMany("Registros")
                        .HasForeignKey("ChamadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiarioX.Server.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Chamada");
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.Disciplina", b =>
                {
                    b.HasOne("DiarioX.Server.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.DisciplinaEtapaEnsino", b =>
                {
                    b.HasOne("DiarioX.Server.Domain.Entities.Disciplina", "Disciplina")
                        .WithMany("EtapasEnsino")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiarioX.Server.Domain.Entities.EtapaEnsino", "EtapaEnsino")
                        .WithMany()
                        .HasForeignKey("EtapaEnsinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiarioX.Server.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Disciplina");

                    b.Navigation("EtapaEnsino");
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.EmailLog", b =>
                {
                    b.HasOne("DiarioX.Server.Domain.Entities.EmailTemplate", "Template")
                        .WithMany("EmailLogs")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Template");
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.Escola", b =>
                {
                    b.HasOne("DiarioX.Server.Domain.Entities.User", "Diretor")
                        .WithMany()
                        .HasForeignKey("DiretorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DiarioX.Server.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Diretor");
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.EtapaEnsino", b =>
                {
                    b.HasOne("DiarioX.Server.Domain.Entities.ModalidadeEnsino", "ModalidadeEnsino")
                        .WithMany()
                        .HasForeignKey("ModalidadeEnsinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiarioX.Server.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ModalidadeEnsino");
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.ModalidadeEnsino", b =>
                {
                    b.HasOne("DiarioX.Server.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("DiarioX.Server.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.PerfilPermissao", b =>
                {
                    b.HasOne("DiarioX.Server.Domain.Entities.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiarioX.Server.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.PeriodoAvaliativo", b =>
                {
                    b.HasOne("DiarioX.Server.Domain.Entities.AnoLetivo", "AnoLetivo")
                        .WithMany("Periodos")
                        .HasForeignKey("AnoLetivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiarioX.Server.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnoLetivo");
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.Professor", b =>
                {
                    b.HasOne("DiarioX.Server.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiarioX.Server.Domain.Entities.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_professores_usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.ProfessorAlocacao", b =>
                {
                    b.HasOne("DiarioX.Server.Domain.Entities.Disciplina", "Disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiarioX.Server.Domain.Entities.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiarioX.Server.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiarioX.Server.Domain.Entities.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disciplina");

                    b.Navigation("Professor");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.ProfessorDisciplina", b =>
                {
                    b.HasOne("DiarioX.Server.Domain.Entities.Disciplina", "Disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_professor_disciplinas_disciplinas");

                    b.HasOne("DiarioX.Server.Domain.Entities.Professor", "Professor")
                        .WithMany("ProfessorDisciplinas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_professor_disciplinas_professores");

                    b.HasOne("DiarioX.Server.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Disciplina");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.ProfessorEscola", b =>
                {
                    b.HasOne("DiarioX.Server.Domain.Entities.Escola", "Escola")
                        .WithMany()
                        .HasForeignKey("EscolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_professor_escolas_escolas");

                    b.HasOne("DiarioX.Server.Domain.Entities.Professor", "Professor")
                        .WithMany("ProfessorEscolas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_professor_escolas_professores");

                    b.HasOne("DiarioX.Server.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Escola");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.Turma", b =>
                {
                    b.HasOne("DiarioX.Server.Domain.Entities.AnoLetivo", "AnoLetivo")
                        .WithMany()
                        .HasForeignKey("AnoLetivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiarioX.Server.Domain.Entities.Escola", "Escola")
                        .WithMany()
                        .HasForeignKey("EscolaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiarioX.Server.Domain.Entities.EtapaEnsino", "EtapaEnsino")
                        .WithMany()
                        .HasForeignKey("EtapaEnsinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiarioX.Server.Domain.Entities.ModalidadeEnsino", "ModalidadeEnsino")
                        .WithMany()
                        .HasForeignKey("ModalidadeEnsinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiarioX.Server.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnoLetivo");

                    b.Navigation("Escola");

                    b.Navigation("EtapaEnsino");

                    b.Navigation("ModalidadeEnsino");
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.User", b =>
                {
                    b.HasOne("DiarioX.Server.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.UsuarioPerfil", b =>
                {
                    b.HasOne("DiarioX.Server.Domain.Entities.Escola", "Escola")
                        .WithMany()
                        .HasForeignKey("EscolaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DiarioX.Server.Domain.Entities.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiarioX.Server.Domain.Entities.User", "Usuario")
                        .WithMany("UsuariosPerfis")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Escola");

                    b.Navigation("Perfil");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.AnoLetivo", b =>
                {
                    b.Navigation("Periodos");
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.Chamada", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.Disciplina", b =>
                {
                    b.Navigation("EtapasEnsino");
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.EmailTemplate", b =>
                {
                    b.Navigation("EmailLogs");
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.Professor", b =>
                {
                    b.Navigation("ProfessorDisciplinas");

                    b.Navigation("ProfessorEscolas");
                });

            modelBuilder.Entity("DiarioX.Server.Domain.Entities.User", b =>
                {
                    b.Navigation("UsuariosPerfis");
                });
#pragma warning restore 612, 618
        }
    }
}
